In [1]:
import numpy as np
print(np.__version__)

2.1.1


# Creación y manipulación de arrays
### Crear un array de 10 elementos enteros aleatorios entre 1 y 100
Usé la función `np.random.randint()` para generar un array de 10 números enteros aleatorios en el rango de 1 a 100 (incluyendo el 1 y excluyendo el 101). El argumento `size=10` especifica que queremos 10 números en el array.

In [3]:
import numpy as np
array_aleatorio = np.random.randint(1, 101, size=10)
print(array_aleatorio)

[42 56  2 93 45  6 62 66 46 92]


### Reshape: A partir del array anterior, convierte este array en una matriz de 2x5.
Igual que antes, importamos la librería NumPy.Generamos el mismo array aleatorio de 10 elementos que creamos. Ahora Redimensionamos la matriz = array_aleatorio.reshape(2, 5) redimensiona el array a una matriz de 2 filas y 5 columnas. Cuando usamos reshape cambia la forma de un array sin cambiar sus datos. Es decir, los mismos 10 elementos se reorganizan en una nueva estructura.

In [5]:
import numpy as np
array_aleatorio = np.array([42, 56,  2, 93, 45,  6, 62, 66, 46, 92])
matriz = array_aleatorio.reshape(2, 5)
print(matriz)

[[42 56  2 93 45]
 [ 6 62 66 46 92]]


### Indexación y slicing: De la matriz obtenida, extrae la primera fila y la última columna. Imprime ambos resultados por separado.
matriz[0, :]: Aquí, 0 indica voy a acceder a la primera fila y los dos puntos indican que quiero todos los elementos de esa fila.
Y para extraer la última columna matriz[:, -1]: Aquí, : indica que quiero todas las filas. El -1 indica que quiero el último elemento de cada fila, es decir, la última columna.

In [2]:
import numpy as np
array_aleatorio = np.array([42, 56,  2, 93, 45,  6, 62, 66, 46, 92])
matriz = array_aleatorio.reshape(2, 5)
primera_fila = matriz[0, :]
ultima_columna = matriz[:, -1]
print("Primera fila:")
print(primera_fila)
print("Última columna:")
print(ultima_columna)

Primera fila:
[42 56  2 93 45]
Última columna:
[45 92]


### Modificación: Cambia el valor de los elementos en la segunda fila a ceros.
matriz[1, :] = 0: Esta línea es donde se cambia la segunda fila.
matriz[1] selecciona la segunda fila 
: indica que quiero seleccionar todos los elementos de esa fila.
= 0 asigna el valor 0 a todos los elementos seleccionados.

In [8]:
import numpy as np
array_aleatorio = np.array([42, 56,  2, 93, 45,  6, 62, 66, 46, 92])
matriz = array_aleatorio.reshape(2, 5)
matriz[1, :] = 0
print(matriz)

[[42 56  2 93 45]
 [ 0  0  0  0  0]]


# Operaciones básicas con NumPy 
### Operaciones aritméticas
Primero, generamos dos arrays de 5 elementos enteros aleatorios entre 1 y 50. Utilizamos `np.random.randint()` para esto, lo que nos permite crear arrays de números aleatorios en un rango especificado.Luego, multiplicamos los dos arrays de la misma manera. La multiplicación también se realiza elemento a elemento.Finalmente, calculamos el promedio y la desviación estándar de los resultados obtenidos de la multiplicación. Utilizamos np.mean() para calcular el promedio y np.std() para calcular la desviación estándar.

In [6]:
# Crear dos arrays de 5 elementos enteros aleatorios entre 1 y 50
array1 = np.random.randint(1, 51, size=5)
array2 = np.random.randint(1, 51, size=5)

# Sumar ambos arrays
suma = array1 + array2
print("\nSuma de los arrays:\n", suma)

# Multiplicar ambos arrays
multiplicacion = array1 * array2
print("\nMultiplicación de los arrays:\n", multiplicacion)

# Calcular el promedio y la desviación estándar de los resultados
promedio = np.mean(multiplicacion)
desviacion_estandar = np.std(multiplicacion)
print("\nPromedio de la multiplicación:", promedio)
print("Desviación estándar de la multiplicación:", desviacion_estandar)


Suma de los arrays:
 [52 57 43 74 49]

Multiplicación de los arrays:
 [ 675  806  222 1360  528]

Promedio de la multiplicación: 718.2
Desviación estándar de la multiplicación: 375.1993603406061


### Condiciones lógicas
Creamos un array de 20 números aleatorios entre 0 y 1. Luego, se ocupan condiciones lógicas para reemplazar los valores menores a 0.5 con 0 y los valores mayores o iguales a 0.5 con 1. 
Primero, se hace un array con 20 números aleatorios en el rango [0, 1). Para esto, usamos `np.random.rand()` que genera números aleatorios en ese rango.En NumPy, podemos usar condicionales directamente sobre el array, lo que genera una máscara booleana que indica qué elementos cumplen la condición. De manera similar, podemos aplicar otra condición lógica para reemplazar los valores mayores o iguales a 0.5 por 1.

In [5]:
array_condiciones = np.random.rand(20)
array_condiciones[array_condiciones < 0.5] = 0
array_condiciones[array_condiciones >= 0.5] = 1
print("\nArray después de aplicar condiciones lógicas:\n", array_condiciones)


Array después de aplicar condiciones lógicas:
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0.]


### Producto escalar
Se hacen dos matrices de 3x3 y  se calcula el producto escalar entre ellas usando `np.dot()`. Este método realiza la multiplicación matricial de manera eficiente.

In [8]:
array_3x3_1 = np.random.randint(1, 11, size=(3, 3))
array_3x3_2 = np.random.randint(1, 11, size=(3, 3))
producto_escalar = np.dot(array_3x3_1, array_3x3_2)
print("\nProducto escalar de las matrices 3x3:\n", producto_escalar)


Producto escalar de las matrices 3x3:
 [[143 118 186]
 [ 88  80  91]
 [128 106 166]]


# Análisis de datos con NumPy 
### Matriz de datos
En esta sección, creamos una matriz de datos que simula mediciones de 5 personas, con 4 atributos: peso, altura, edad y presión arterial. Para organizar mejor los datos, utilice un DataFrame de la librería **Pandas**, lo que facilita el acceso a los datos y su análisis y me ayuda para hacerlo visual y poder entenderle. 
Primero, generamos una matriz de datos aleatorios utilizando `np.random.randint()` de NumPy. Luego utilice **Pandas** para convertir la matriz en un DataFrame y asignar nombres tanto a las columnas como a las filas.
y por ultimo en df.index = ['Persona 1', 'Persona 2', 'Persona 3', ...]: Asigno etiquetas a las filas para que cada una represente a una persona en lugar de números de índice.

### Estadísticas
1. **Calcular la media de cada columna**:
   Para calcular la media de cada medición (peso, altura, edad, presión arterial), utilizamos la función `np.mean()` de **NumPy** con `axis=0` para que el cálculo se realice a lo largo de las columnas.

2. **Encontrar el valor máximo y mínimo de cada fila**:
   Utilizamos las funciones `np.max()` y `np.min()` de **NumPy** con `axis=1` para encontrar los valores máximo y mínimo de cada fila (que representan a las personas).

3. **Ordenar las filas según la columna 'peso'**:
   Para ordenar las filas según la columna "peso", usamos `np.argsort()` de **NumPy** para obtener los índices que ordenan el array y luego reorganizamos el DataFrame usando esos índices. También, **Pandas** ofrece una función directa `sort_values()` para hacer este tipo de ordenamientos.
Estas operaciones nos permiten analizar los datos de manera eficiente y observar las mediciones de cada persona de forma más clara.

In [5]:
import numpy as np
import pandas as pd

datos_personas = np.random.randint(1, 21, size=(5, 4))
columnas = ['peso', 'altura', 'edad', 'presion_arterial']
df = pd.DataFrame(datos_personas, columns=columnas)
df.index = ['Persona 1', 'Persona 2', 'Persona 3', 'Persona 4', 'Persona 5']

print("Datos originales:\n", df)

# 1. Calcular la media de cada columna
media_columnas = np.mean(df, axis=0)
print("\nMedia de cada columna:\n", media_columnas)

# 2. Encontrar el valor máximo y mínimo de cada fila
max_filas = np.max(df.values, axis=1)
min_filas = np.min(df.values, axis=1)
print("\nValor máximo de cada fila:\n", max_filas)
print("\nValor mínimo de cada fila:\n", min_filas)

# 3. Ordenar las filas según la columna "peso"
sorted_indices = np.argsort(df['peso'].values)
df_sorted_numpy = df.iloc[sorted_indices]
print("\nFilas ordenadas según la columna 'peso':\n", df_sorted_numpy)

Datos originales:
            peso  altura  edad  presion_arterial
Persona 1    10      17     5                 1
Persona 2     9       6    13                16
Persona 3     5      12    10                19
Persona 4    14       3    20                14
Persona 5    16       6    17                 5

Media de cada columna:
 peso                10.8
altura               8.8
edad                13.0
presion_arterial    11.0
dtype: float64

Valor máximo de cada fila:
 [17 16 19 20 17]

Valor mínimo de cada fila:
 [1 6 5 3 5]

Filas ordenadas según la columna 'peso':
            peso  altura  edad  presion_arterial
Persona 3     5      12    10                19
Persona 2     9       6    13                16
Persona 1    10      17     5                 1
Persona 4    14       3    20                14
Persona 5    16       6    17                 5
